title: Products Module
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: Content
          fields:
             header.title:
              type: text
              label: Section Title
              default: 'Community Market'

             header.hide_demo:
                type: toggle
                label: Hide Demo Content
                default: 0
                options:
                    1: PLUGIN_ADMIN.YES
                    0: PLUGIN_ADMIN.NO
            
             header.products:
              type: list
              label: Products
              fields:
                .image:
                  type: file
                  label: Product Image
                  destination: 'self@'
                  multiple: false
                  limit: 1
                .name:
                  type: text
                  label: Product Name
                .price:
                  type: text
                  label: Price (e.g., $15.00)
                .type:
                  type: select
                  label: Type
                  options:
                    physical: Physical
                    digital: Digital
                .link:
                  type: text
                  label: Product Link
                  default: '#'
